### ISSUE TITLE
Disabling sidenotes

### ISSUE THREAD

**Issue by adriancaruana** [mrtzh/unbuch#10]
The examples in the README ([Patterns, Predictions, and Actions](https://mlstory.org/) and [Fairness and Machine Learning](https://fairmlbook.org/)) have PDFs without sidenotes. I cannot seem to find an option to disable sidenotes in the `tufts-book` class, nor elsewhere in this repo. I've tried removing the `sidenotes.py` filter from the various commands in the `Makefile`.

How can I disable the sidenotes in the generated PDFs?

**Comment by mrtzh** [comment]
The easiest way is to change the documentclass in `templates/book.tex` to whatever you want. Then map the `\marginnote` command to whatever else you want, e.g., `\footnote`. This is not something that I intend to support as an option in this package. There are all sorts of ways to customize the layout by editing the template files.
