### ISSUE TITLE
`make html` not completing

### ISSUE THREAD

**Issue by adamgayoso** [mrtzh/unbuch#7]
I was looking into this project and found that `make html` was not working.

I received the following message:

```
make: *** No rule to make target `css/pandoc.css', needed by `publish/style.css'.  Stop.
```

I believe deleting these lines fixes it.

https://github.com/mrtzh/unbuch/blob/067229e255d96a45ce0cbea5296f47b2b41cde17/Makefile#L25-L26

**Comment by mrtzh** [comment]
Addressed by https://github.com/mrtzh/unbuch/pull/6
